"""Add phone column to applicants table

Revision ID: 50579087b079
Revises: aea071bc8589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql  # <-- FIX 1: IMPORT DITAMBAHKAN

# revision identifiers, used by Alembic.
revision = '50579087b079'
down_revision = 'aea071bc8589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Ini adalah perintah yang kita inginkan dari migrasi ini
    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        # FIX 2: Perintah batch_op.drop_index(...) yang salah telah dihapus dari sini

    # Ini adalah perintah dari migrasi SEBELUMNYA (aea071...)
    # yang mungkin gagal dan digabungkan ke sini oleh Alembic.
    # Kita biarkan ini di sini untuk memastikan ENUM diubah.
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=mysql.ENUM('Pending', 'Diterima', 'Ditolak'),
            type_=sa.Enum('pending', 'accepted', 'rejected'),
            existing_nullable=False,
            existing_server_default=sa.text("'Pending'"))

    # FIX 2: Perintah drop_index lain yang salah untuk tabel lain telah dihapus.
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Kebalikan dari perintah di atas
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=sa.Enum('pending', 'accepted', 'rejected'),
            type_=mysql.ENUM('Pending', 'Diterima', 'Ditolak'),
            existing_nullable=False,
            existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('applicants', schema=None) as batch_op:
        batch_op.drop_column('phone')
        
    # FIX 2: Perintah create_index yang salah telah dihapus.

    # ### end Alembic commands ###