"""Update application status enum to English

Revision ID: aea071bc8589
Revises: eee2a9894972
Create Date: 2025-11-13 00:56:53.409537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea071bc8589'
down_revision = 'eee2a9894972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=mysql.ENUM('Pending', 'Diterima', 'Ditolak'),
            type_=sa.Enum('pending', 'accepted', 'rejected'),
            existing_nullable=False,
            server_default=sa.text("'pending'")) # <-- Tambahkan default server baru

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
            existing_type=sa.Enum('pending', 'accepted', 'rejected'),
            type_=mysql.ENUM('Pending', 'Diterima', 'Ditolak'),
            existing_nullable=False,
            server_default=sa.text("'Pending'")) # <-- Kembalikan default lama

    # ### end Alembic commands ###